on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Release Multi Platform

jobs:
  build-macos:
    name: Upload Release Asset macOS
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.6]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U -r requirements/base.txt
          pip install -U -r requirements/mac.txt
      - name: Run fbs
        run: |
          fbs freeze
          fbs installer
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/Ephemeris.dmg
          asset_name: Ephemeris.dmg
          tag: ${{ github.ref }}
          overwrite: true

  build-windows:
    name: Upload Release Asset Windows
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.6]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U -r requirements/base.txt
      - name: Run fbs and freeze application
        run: |
          fbs freeze
          fbs installer
      - name: Code signing
        uses: CyR1en/code-sign-action@v6
        with:
          certificate: ${{ secrets.CERTIFICATE }}
          password: ${{secrets.CERTIFICATE_PASSWORD }}
          certificatesha1: ${{ secrets.CERTIFICATESHA1 }}
          timestampUrl: 'http://ts.ssl.com'
          folder: target/
          recursive: false
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/EphemerisSetup.exe
          asset_name: EphemerisSetup.exe
          tag: ${{ github.ref }}
          overwrite: true
